### ISSUE TITLE
Group by heading beta feature failing

### ISSUE THREAD

**Issue by BitsByD** [benbalter/comment-rollup#83]
### Describe the bug

With the beta `group_by_heading` set to true I see fresh content added to a Discussion. However, the content is not grouped by headings: it appends all existing Discussion comments in sequence.

### Steps to reproduce the behavior

1. Use a `/snippet` or similar slash command to ensure the a new Discussion comment has predictable and exactly the same headings across multiple comments.
2. Configure the a workflow as follows:

```yaml
on: 
  discussion_comment: {} # Remove to only rollup issue comments

name: Rollup weekly snippets

jobs:
  comment_rollup:
    runs-on: ubuntu-latest
    name: Comment rollup

    steps:
      - name: Rollup comments
        uses: benbalter/comment-rollup@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          group_by_heading: true
```

4. Add two comments on the same discussion using the exact same headings.

### Expected behavior

See the content from both discussion posts grouped under a singular heading-per-section in the collapsed Details area in the Discussion.

Running this in the TPM LT repo.
